#!/bin/zsh
yabai -m config focus_follows_mouse autoraise
yabai -m config mouse_follows_focus on 
yabai -m config focus_follows_mouse off

# yabai -m config window_shadow  float
# yabai -m config window_topmost on

yabai -m config layout         bsp
yabai -m config top_padding    2
yabai -m config bottom_padding 2
yabai -m config left_padding   2
yabai -m config right_padding  2
yabai -m config window_gap     2
# pading for status bar
# yabai -m config external_bar main:20:0
yabai -m config external_bar all:0:20

yabai -m config --space 2 layout float
yabai -m config window_topmost on
# modify window shadows (default: on, options: on, off, float)
# example: show shadows only for floating windows
yabai -m config window_shadow float

# window opacity (default: off)
# example: render all unfocused windows with 90% opacity
# yabai -m config window_opacity on
# yabai -m config active_window_opacity 1.0
# yabai -m config normal_window_opacity 0.9

# yabai -m rule --add app="Emacs" manage=on
# yabai -m rule --add app=zathura manage=on
yabai -m rule --add app="System Preferences" manage=off
yabai -m rule --add app="Google Drive" manage=off
# yabai -m rule --add app="Acrobat Pro DC" manage=on
yabai -m rule --add app="VLC" manage=off
yabai -m rule --add app="System Information" manage=off
yabai -m rule --add app="Toggl Track" manage=off

# yabai -m rule --add app="Firefox" manage=on
yabai -m rule --add app="Firefox" title="Opening .*$" manage=off  
# yabai -m rule --add app="Firefox" title="" manage=off  
# yabai -m rule --add app="Firefox" title="Settings" manage=off  
# yabai -m rule --add app="Firefox" title="Mozilla Firefox" manage=off  
yabai -m rule --add app="Firefox" title="Library" manage=off  
